import { AttributeKugi } from "./attributeKugi";
import { HistoryDraft } from "./historyDraft";
import { MapsetSource } from "./mapsetSource";
import { MapsetType } from "./mapsetType";
import { Organization } from "./organization";
import { Topic } from "./topic";
import { User } from "./user";

export type Mapset = {
  id: string;
  name: string;
  slug: string;
  description: string;
  scale: string;
  wilayah_id: number | null;
  owner: string;
  owner_address: string;
  owner_telephone: string;
  owner_email: string;
  shp: string;
  update_period: string;
  revision_date: string;
  klasifikasi: string;
  validate: string;
  topik: Topic;
  organisasi: Organization;
  mapsetservice_url: string;
  metadata_xml: string;
  mapset_type: MapsetType;
  mapset_source: MapsetSource;
  mapset_program: Record<string, unknown>;
  mapset_coverage: Record<string, unknown>;
  count_view_satudata: number;
  count_view_satupeta: number;
  count_download_dataset: number;
  count_download_image: number;
  count_download_shp: number;
  count_download_geojson: number;
  history_draft: HistoryDraft[];
  attribute_kugi: AttributeKugi[];
  is_permanent: boolean;
  is_popular: boolean;
  is_active: boolean;
  is_deleted: boolean;
  user: User;
  cuid: number;
  cdate: string;
  muid: number;
  mdate: string;
};
