import { AttributeKugi } from "./attribute-kugi";
import { Category } from "./category";
import { HistoryDraft } from "./history-draft";
import { MapsetSource } from "./mapset-source";
import { MapsetType } from "./mapset-type";
import { Topic } from "./topic";
import { UserResponse } from "./user";

export type Mapset = {
  id: number;
  name: string;
  slug: string;
  description: string;
  scale: string;
  wilayah_id: number | null;
  owner: string;
  owner_address: string;
  owner_telephone: string;
  owner_email: string;
  shp: string;
  update_period: string;
  revision_date: string;
  klasifikasi: string;
  validate: string;
  topik: Topic;
  mapsetservice_url: string;
  layer_url: string;
  metadata_xml: string;
  mapset_type: MapsetType;
  mapset_source: MapsetSource;
  mapset_program: Record<string, unknown>;
  mapset_coverage: Record<string, unknown>;
  count_view_satudata: number;
  count_view_satupeta: number;
  count_download_dataset: number;
  count_download_image: number;
  count_download_shp: number;
  count_download_geojson: number;
  history_draft: HistoryDraft[];
  attribute_kugi: AttributeKugi[];
  is_permanent: boolean;
  is_popular: boolean;
  is_active: boolean;
  is_deleted: boolean;
  user?: UserResponse;
  cuid: number;
  cdate: string;
  muid: number;
  mdate: string;
  category: Category;
};
